module.exports = [
    {
        destination: "Kraków",
        description:
            "Kraków (łac. Cracovia, niem. Krakau, jid. ‏קראָקע Kroke‎) – miasto na prawach powiatu położone w południowej Polsce nad Wisłą, drugie co do liczby mieszkańców[1] i powierzchni miasto kraju[1], formalna stolica Polski do 1795 r. i miasto koronacyjne oraz nekropolia królów Polski, od 1000 r. nieprzerwanie stolica diecezji krakowskiej (jednej z pięciu w ówczesnej Polsce), a od 1925 archidiecezji i metropolii. Lokowany przed 1228 rokiem, ponownie w 1257 r.[5]. Od odzyskania niepodległości w 1918 r. miasto wojewódzkie (od 1998 r. siedziba władz województwa małopolskiego), jest także centralnym ośrodkiem metropolitalnym aglomeracji krakowskiej i Krakowskiego Obszaru Metropolitalnego. Kraków uznawany jest za stolicę historycznej Małopolski. Leży na obszarze Bramy Krakowskiej, Niecki Nidziańskiej i Pogórza Zachodniobeskidzkiego.",
        logo: "logo.jpg",
        gallery: JSON.stringify(["gallery-item-0.jpg", "gallery-item-1.jpg", "gallery-item-2.jpg", "gallery-item-3.jpg", "gallery-item-4.jpg", "gallery-item-5.jpg"]),
        start: "2021-01-13",
        end: "2021-01-23",
        price: 1000,
        activities: JSON.stringify([
            "Parki i ochrona przyrody",
            "Rezerwaty i pomniki przyrody",
            "Użytki ekologiczne",
            "Uzdrowiska",
            "Zanieczyszczenie powietrza",
            "Średniowiecze",
            "Dzieje nowożytne (XVI – XIX wiek)",
            "Architektura",
            "Narodowe Centrum Radioterapii Hadronowej;",
            "Centrum Onkologii Instytut im. M. Skłodowskiej-Curie;",
            "Szpital Uniwersytecki w Krakowie",
            "Uniwersytecka Klinika Stomatologiczna w Krakowie",
            "Uniwersytecki Szpital Dziecięcy w Krakowie",
            " Krakowskie Centrum Rehabilitacji i Ortopedii",
            "Szpital Położniczo-Ginekologiczny Ujastek",
            "5 Wojskowy Szpital Kliniczny z Polikliniką im. Mariana Garlickiego",
        ]),
        turistBonPayment: "true",
        path: "2021-01-13_Kraków",
    },
    {
        destination: "Berlin",
        description:
            "Berlin – stolica, największe miasto Niemiec i zarazem kraj związkowy. Zajmuje powierzchnię ok. 892 km² i zamieszkuje go około 3,7 mln osób[2]. Jest największym miastem w Unii Europejskiej pod względem liczby mieszkańców. Berlin jest podzielony na dwanaście okręgów administracyjnych (Bezirk). Przez przestrzeń miejską przepływają m.in. rzeki Sprewa i Hawela, a ponadto znajduje się wiele jezior i zatok, w tym największe Müggelsee. Pierwsza wzmianka o mieście pochodzi z 1237 r. Berlin pełnił rolę historycznej stolicy Brandenburgii, Królestwa Prus, Związku Północnoniemieckiego, Cesarstwa Niemieckiego, tzw. Republiki Weimarskiej i tzw. III Rzeszy. Po 1945 r. wschodnia część miasta była stolicą Niemieckiej Republiki Demokratycznej (Berlin, Hauptstadt der DDR), natomiast pozostała tworzyła Berlin Zachodni – otoczoną murem (okres 1961-89) enklawę na terenie NRD. Po Zjednoczeniu Niemiec 1990 roku Berlin został stolicą całych Niemiec.",
        logo: "logo.jpg",
        gallery: JSON.stringify(["gallery-item-0.jpg", "gallery-item-1.jpg", "gallery-item-2.jpg", "gallery-item-3.jpg", "gallery-item-4.jpg"]),
        start: "2021-01-19",
        end: "2021-01-29",
        price: 3000,
        activities: JSON.stringify([
            "Wolny Uniwersytet Berliński ",
            "Uniwersytet Humboldtów w Berlinie",
            "Uniwersytet Techniczny w Berlinie ",
            "Uniwersytet Sztuk Pięknych w Berlinie ",
            "Wyższa Szkoła Techniki i Gospodarki w Berlinie",
            "Wyższa Szkoła Techniki im. Beutha w Berlinie",
            "Europejska Szkoła Zarządzania i Techniki",
            "Brama Brandenburska",
            "Zwiedzanie Reichstag",
            "Mur Berliński ",
            "Siegessäule",
            "Pałac Charlottenburg",
            "Nowa Synagoga",
            "Cmentarz żydowski w Berlinie-Weißensee",
        ]),
        turistBonPayment: "true",
        path: "2021-01-19_Berlin",
    },
    {
        destination: "Gdańsk",
        description:
            "Gdańsk z 471 525 mieszkańcami[5] zajmuje szóste miejsce w Polsce pod względem liczby ludności, a siódme miejsce pod względem powierzchni – 263,44 km²[4]. Ośrodek aglomeracji trójmiejskiej, nazywaną też gdańską, wraz z Gdynią i Sopotem tworzą Trójmiasto. Jest to miasto o ponadtysiącletniej historii, którego tożsamość na przestrzeni wieków kształtowała się pod wpływem różnych kultur. Gdańsk był również największym miastem Rzeczypospolitej Obojga Narodów, miastem królewskim i hanzeatyckim[9], posiadał prawo do czynnego uczestnictwa w akcie wyboru króla[10], w XVI w. był najbogatszym w Rzeczypospolitej[11]. Miasto było też ważnym ośrodkiem kulturalnym. Gdańsk uznawany jest za symboliczne miejsce wybuchu II wojny światowej oraz początku upadku komunizmu w Europie Środkowej. Na terenie miasta znajdują się liczne zabytki architektury, działa w nim wiele instytucji i placówek kulturalnych.",
        logo: "logo.jpg",
        gallery: JSON.stringify(["gallery-item-0.jpg", "gallery-item-1.jpg", "gallery-item-2.jpg", "gallery-item-3.jpg"]),
        start: "2021-03-18T00:00:00.000Z",
        end: "2021-03-24T00:00:00.000Z",
        price: 800,
        activities: JSON.stringify([
            "Gdańska Wyższa Szkoła Humanistyczna",
            "Wyższa Szkoła Turystyki i Hotelarstwa w Gdańsku ",
            "Hala Ergo Arena, znajdująca się na granicy Gdańska i Sopotu",
            "Stadion Energa Gdańsk",
            "Przystań żaglowa na Nowej Motławie",
            "Kąpielisko morskie Gdańsk Brzeźno",
            "Molo Gdańsk Brzeźno ",
            "Forum Gdańsk",
        ]),
        turistBonPayment: "true",
        path: "2021-03-18_Gdańsk",
    },
];
